Dit is een demonstratie van enkele van de mogelijkheden van Jupyter Notebooks.

## Interactie: widgets

Het is soms omslachtig om de programmatekst te veranderen voor het uitproberen van de effecten van verschillende waarden voor een parameter. Met behulp van Widgets kun je dit soort experimenten interactief maken.



In [6]:
# Enabling the `widget` backend.
# This requires jupyter-matplotlib a.k.a. ipympl.
# ipympl can be install via pip or conda.
%matplotlib widget

In [7]:
import ipywidgets as widgets

In [8]:
from IPython.display import display
w = widgets.IntSlider()
display(w)

IntSlider(value=0)

In [9]:

out = widgets.Output(layout={'border': '1px solid black'})
out

Output(layout=Layout(border='1px solid black'))

In [13]:
with out:
    for i in range(10):
        print(i, 'Hello world!')

In [14]:
with out: print("Hi there")

NB: we kunnen dit ook gebruiken om in verschillende stappen de uitvoer van bijv. een Turtle gfx programma op te bouwen?


In [15]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

def f(m, b): # with the interactive widget parameters
    # plt.figure(2)
    fig, ax = plt.subplots()

    plt.ylim(-10, 11)
    plt.xlim(-10, 11)
    plt.axis("equal") # for square grid (correct angles)
    plt.xlabel("x")
    plt.ylabel("y")
    
    # Major ticks every 2 minor ticks every 1
    major_ticks = np.arange(-10, 11, 2)
    minor_ticks = np.arange(-10, 11, 1)

    ax.set_xticks(major_ticks)
    ax.set_xticks(minor_ticks, minor=True)
    ax.set_yticks(major_ticks)
    ax.set_yticks(minor_ticks, minor=True)

    # And a corresponding grid
    plt.grid(which='minor', color="b", alpha=0.2)
    plt.grid(which='major', color='b', alpha=0.6)
    
    x = np.linspace(-10, 11, num=1000)
    plt.plot(x, m * x + b) # the function...
    plt.suptitle("linear function: y=m*x + b")

    # plt.grid(True)
    plt.show()


In [16]:
interactive_plot = widgets.interactive(f, m=(-2.0, 2.0), b=(-3, 3, 0.5))
interactive_plot

interactive(children=(FloatSlider(value=0.0, description='m', max=2.0, min=-2.0), FloatSlider(value=0.0, descr…

In [9]:
np.arange(-6, 7, 1)

array([-6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [10]:
np.arange(-6, 7, 2)

array([-6, -4, -2,  0,  2,  4,  6])

In [11]:
# Enabling the `widget` backend.
# This requires jupyter-matplotlib a.k.a. ipympl.
# ipympl can be install via pip or conda.
%matplotlib widget

In [13]:
# Testing matplotlib interactions with a simple plot

import matplotlib.pyplot as plt
import numpy as np

plt.figure(1)
plt.plot(np.sin(np.linspace(0, 20, 100)))
plt.show()

In [4]:
from mpl_toolkits.mplot3d import axes3d

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

# Grab some test data.
X, Y, Z = axes3d.get_test_data(0.05)

# Plot a basic wireframe.
ax.plot_wireframe(X, Y, Z, rstride=10, cstride=10)

fig.canvas.layout.max_width = '800px'

plt.show()

NameError: name 'plt' is not defined

In [ ]:
from ipycanvas import Canvas

canvas = Canvas(size=(200, 200))

canvas.fill_rect(25, 25, 100, 100)
canvas.clear_rect(45, 45, 60, 60)
canvas.stroke_rect(50, 50, 50, 50)

display(canvas)
3

In [ ]:
canvas.clear()
display(canvas)

## Geïnstalleerde extensies

Welke extensies hebben we geïnstalleerd (met conda)?

* https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Basics.html
    * Jupyter widgets
* Jupyter nb_conda
    * om in een notebook met conda-omgevingen te werken (nog verder uitzoeken)
* matplotlib
* widget-versie van matplotlib
* mongodb interface? pymongo
* ipysheets?
* nbgrader
* spreadsheat-extensie: ipysheet
* rise (voor slides; werkt alleen met notebook, niet met lab)

In [20]:
import numpy as np
from ipysheet import from_array, to_array

arr = np.random.randn(6, 10)

sheet = from_array(arr)
sheet

Sheet(cells=(Cell(column_end=9, column_start=0, row_end=5, row_start=0, squeeze_column=False, squeeze_row=Fals…

In [21]:
arr = np.array([True, False, True])

sheet = from_array(arr)
sheet

Sheet(cells=(Cell(column_end=0, column_start=0, numeric_format=None, row_end=2, row_start=0, squeeze_row=False…

In [22]:
to_array(sheet)

array([[ True],
       [False],
       [ True]])

In [23]:
import numpy as np
import pandas as pd
from ipysheet import from_dataframe
from ipywidgets import Text, VBox, link

df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                   'D': np.array([False, True, False, False], dtype='bool'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})

df.loc[[0, 2], ['B']] = np.nan


s = from_dataframe(df)

search_box = Text(description='Search:')
link((search_box, 'value'), (s, 'search_token'))

VBox((search_box, s))

In [24]:
from ipywidgets import FloatSlider, IntSlider, Image
import ipysheet

slider = FloatSlider()
slider

FloatSlider(value=0.0)

In [25]:
sheet = ipysheet.sheet()

cell1 = ipysheet.cell(0, 0, slider, style={'min-width': '150px'})
cell3 = ipysheet.cell(2, 2, 42.)
cell_sum = ipysheet.cell(3, 2, 42.)

@ipysheet.calculation(inputs=[(cell1, 'value'), cell3], output=cell_sum)
def calculate(a, b):
    return a + b

sheet

Sheet(cells=(Cell(column_end=0, column_start=0, row_end=0, row_start=0, style={'min-width': '150px'}, type='wi…

In [26]:
slider2 = IntSlider()
cell1.value = slider2
slider2

IntSlider(value=0)

In [27]:
sheet = ipysheet.sheet()

column1 = ipysheet.column(0, [FloatSlider() for _ in range(5)])
column2 = ipysheet.column(1, [1.] * 5)

sheet

Sheet(cells=(Cell(column_end=0, column_start=0, row_end=4, row_start=0, squeeze_row=False, type='widget', valu…

In [28]:
cell = ipysheet.cell(3, 4)
cell.value = "Hi"
cell00 = ipysheet.cell(0,0)
cell00.value

0.0

In [29]:
column1.value = column1.value[:-1] + [IntSlider()]
sheet

Sheet(cells=(Cell(column_end=0, column_start=0, row_end=4, row_start=0, squeeze_row=False, type='widget', valu…

In [30]:
ipysheet.to_dataframe(sheet)

A    B     C     D     E
0                       0  1.0  None  None  None
1  FloatSlider(value=0.0)  1.0  None  None  None
2  FloatSlider(value=0.0)  1.0  None  None  None
3  FloatSlider(value=0.0)  1.0  None  None    Hi
4      IntSlider(value=0)  1.0  None  None  None

In [32]:
sheet = ipysheet.sheet()

column1 = ipysheet.column(0, [Image.from_file('./image.png') for _ in range(5)], style={'min-width': '60px', 'min-height': '50px'})
column2 = ipysheet.column(1, [1.] * 5)

sheet

FileNotFoundError: [Errno 2] No such file or directory: './image.png'